### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by grappler** [openstream/wordpress-de-ch#1]
The time zone should be "Europe/Zurich" not "Europe/Berlin".

**Comment by nickw108** [comment]
Fixed in 0a6231ba51e87d8bb4cff46638b763edfcb7a535, wondering why you didn't suggest Europe/Bern 😂

**Comment by grappler** [comment]
Because it does not exist :smile:

**Comment by nickw108** [comment]
I thought it does, at least in Magento there are both 😄
