### ISSUE TITLE
Improve Berlin/Zurich replacement

### ISSUE THREAD

**Issue by ocean90** [openstream/wordpress-de-ch#4]
For example https://translate.wordpress.org/projects/wp/dev/de-ch/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4518199&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc should use "Zürich" with "ü".

Berlin should also not be replaced in the the wp-dev-cc-de-ch.po file: https://github.com/openstream/wordpress-de-ch/blame/9af653806e706fd0336fa63761c04ae21ce8b95b/core/de_CH/wp-dev-cc-de-ch.po#L554-L556

**Comment by nickw108** [comment]
Thanks for the pointer. Will arrive at Bern contributor day shortly and look into it.

**Comment by nickw108** [comment]
Fixed in aeaf2d8e7a742d5f1a53ee95c6ddca049ebf7184 and d201471518d1087affc08d55e34f53ca979dd4d6.
